Gift and wish creation
attahemma/WisherBirthdayWishApp pull request #28
Opened 2022-04-02 22:19 UTC by khalidtouch

Worked on the Gift and WIsh entities and related them with a one-to-one relationship

2022-04-12 22:00 UTC, Gentlekboy commented
Hi man, @khalidtouch 
Got time to resolve conflicts and make updates from the recently merged code?

2022-04-12 22:00 UTC, attahemma submitted a review, later dismissed

2022-04-12 22:06 UTC, attahemma requested changes
Please update the new changes and make another PR

2022-04-18 11:09 UTC, attahemma approved these changes

2022-04-18 11:10 UTC, merged